name: ci
on:
  push:
    branchs:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run test.
        run: |
          chmod +x test/test.sh
          ./test.sh
